Yummy_a_recipe_app/YummyProject/YummyProject/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls') , name='app' ),
    path('accounts/', include('django.contrib.auth.urls') , name='accounts' ),
    path('',views.homepage , name='homepage' ),
    # path("__reload__/", include("django_browser_reload.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Yummy_a_recipe_app/YummyProject/app/urls.py

from django.urls import path
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # path('', views.home , name='home'),
    path('', views.recipe_list , name='list'),
    path('oldest/', views.oldest , name='oldest'),
    path('popular/', views.popular , name='popular'),
    path('sweet/', views.sweet , name='sweet'),
    path('punjabi/', views.punjabi , name='punjabi'),
    path('indo_chinease/', views.indo_chinease , name='indo_chinease'),
    path('spicy/', views.spicy , name='spicy'),
    path('up_special/', views.up_special , name='up_special'),
    path('recipe/create/', views.recipe_create , name='recipe_create'),
    path('<int:recipe_id>/edit/', views.recipe_edit , name='recipe_edit'),
    path('<int:recipe_id>/view_recipe/', views.view_recipe , name='view_recipe'),
    path('<int:recipe_id>/delete/', views.recipe_delete , name='recipe_delete'),
    path('<int:recipe_id>/like/', views.like_others_post , name='like_others_post'),
    path('register/', views.register , name='register'),
    path('search/', views.search , name='search'),

]

Yummy_a_recipe_app/YummyProject/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

class Yummy(models.Model):
    category_choices =[
        ('sweet','sweet'),
        ("spicy","spicy"),
        ("indo-chinease","indo-chinease"),
        ("punjabi","punjabi"),
        ("UP-special","UP-special"),
        ("new","new"),
    ]

    user = models.ForeignKey(User , related_name='user', on_delete=models.CASCADE)
    recipe_name = models.TextField(max_length=20 , null=True ,blank=True)
    text = models.TextField(max_length=235)
    category = models.CharField(max_length=13, choices= category_choices, null="new")
    likes = models.ManyToManyField(
        # settings.AUTH_USER_MODEL,
         User,
          blank=True, related_name='post_likes')
    images = models.ImageField(upload_to='yummy_images/', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} - {self.text[:5]}'
    
    def curr_recipe_name(self):
        return f"{self.recipe_name}"

    @property
    def view_count(self):
        return RecipeLikes.objects.filter(recipe=self).count()
    
    @property
    def like_or_unlike( self):
        return RecipeLikes.objects.filter(user= self.user, recipe=self).exists()
        
    def isLiked(self, user):
        return RecipeLikes.objects.filter( recipe=self, isLikedPost=True, user= user).exists()


class RecipeLikes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Yummy, on_delete=models.CASCADE)
    # created = models.DateTimeField(auto_now_add=True)
    isLikedPost = models.BooleanField(default=True)

    class Meta :
        unique_together = ('user', 'recipe')
    
    def __str__(self):
        # return f'{self.user.username} likes - {self.recipe.recipe_name}
        return self.user.username
        # return True

Yummy_a_recipe_app/YummyProject/app/templates/home.html
{% extends "base.html" %}
{% block Portfolio %}{% endblock %}

Yummy_a_recipe_app/YummyProject/app/templates/recipe_delete.html
{% extends "base.html" %}
{% block Portfolio %}{% endblock %}
{% block content %}
    <div class="d-flex my-4 del-page">

        <h3 class="m-4" >Are you Sure ?</h3>
        
        <h4 class="m-4">Recipe  will get deleted.</h4>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger m-4">Delete</button>
            {% comment %} <button class="btn btn-secondary"> {% endcomment %}
    
                <a href="{%url 'list'%}" class="btn btn-secondary">Cancel</a>
            {% comment %} </button> {% endcomment %}
        </form>
    </div>


{% endblock %}

Yummy_a_recipe_app/YummyProject/app/templates/recipe_form.html
 {% extends "base.html" %}
{% block Portfolio %}{% endblock %}
{% block content %}
{% comment %}
    {% if form.instance.pk %}
        <h3>Edit Recipe</h3>
    {%else%}
    <h3>Share new Recipe</h3>
    {% endif %}
    <form class='form' method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary m-4" type="submit">Ready To Share</button>
       </form>
   

 {% endcomment %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="my-4 d-flex input">
        <div class="name d-flex mx-2">
            <label for="id_recipe_name" class="form-label text-info m-4">Recipe Name : </label>
           {{form.recipe_name}}
        </div>
        <div class="getImage mx-2">
            <label for="id_images" class="form-label">Upload Image : </label>
            {{ form.images }}
        </div>
    </div>

    <div class="mb-3">
        <label for="id_text" class="form-label ">Recipe : </label>
        {{ form.text }}
    </div>

    <div class="mb-3">
    </div>

    <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock %}

Yummy_a_recipe_app/YummyProject/app/templates/recipe_list.html
{% extends "base.html" %}
{% load custom_filters %}
{% load static %}

{% block Portfolio %}{% endblock %}
{% block content %}



<a href="{%url 'recipe_create'%}" class='btn btn-primary m-4'>
  <img id="pen" src="{%static 'images/pen.svg'%}" alt="">
  share a recipe
</a>
<a href="{%url 'oldest'%}" class='btn btn-secondary mx-2'>
  oldest
</a>
<a href="{%url 'list'%}" class='btn btn-secondary mx-2'>
  newsest
</a>
<a href="{%url 'popular'%}" class='btn btn-secondary mx-2'>
  popular
</a>
<a href="{%url 'up_special'%}" class='btn btn-secondary mx-2'>
  UP Special
</a>
<a href="{%url 'sweet'%}" class='btn btn-secondary mx-2'>
  sweet
</a>
<a href="{%url 'spicy'%}" class='btn btn-secondary mx-2'>
  spicy
</a>
<a href="{%url 'indo_chinease'%}" class='btn btn-secondary mx-2'>
  indo-chinease
</a>
<a href="{%url 'punjabi'%}" class='btn btn-secondary mx-2'>
  punjabi
</a>
<div class="container row gap-3">
  {% block content2 %}{% endblock %}

  <div class="container width">
    <div class="row">
      {% for recipe in recipes %}
    <div class="col-md-3 test2">


      <div class="card mt-2" id='card'>
        <div class="card-img-top card-images img-container">
          
          <img src="{{recipe.images.url}}"  id="card-images"  alt="...">
        </div>
        <div class="card-body card-title">
          <p><h6 class="card-title">{{recipe.user.username}}</h6></p>
          <p class="card-text">{{recipe.recipe_name}} - <span class= "category">
            <b>{{recipe.category}}</b>
          </span></p>

          <div class="like-view d-flex">
            <form method="post" action="{%url 'like_others_post' recipe.id%}">
              {% csrf_token %}
              <button method="post" class="btn btn-muted">
                {% if user %}

                {% if recipe|is_liked_by:user %}
                <img id="like" src="{% static 'images/like.svg' %}" alt="">
            {% else %}
                <img id="unlike" src="{% static 'images/unlike.svg' %}" alt="">
            {% endif %}
                {% endif %}
                
        
            {{recipe.view_count}}
          </button>
        </form>
            
            <a href="{%url 'view_recipe' recipe.id%}" class="btn btn-muted ">
              <img id="view"  src="{%static 'images/view.svg'%}" alt="">
            </a>
            {% if recipe.user == user %}
            
              
  
              
                <a href="{%url 'recipe_edit' recipe.id%}" class="btn btn-muted ">
                  <img id="edit" src="{%static 'images/edit.svg'%}" alt="">
                </a>
                <a href="{%url 'recipe_delete' recipe.id%}" class="btn btn-muted">
                  <img id="delete" src="{%static 'images/delete.svg'%}" alt="">
                </a>

            {% endif %}
          </div>
          
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:4 %}
                </div><div class="row">
            {% endif %}
    
    
      {% endfor %}
    </div>
  </div>

    
</div>
<footer class='d-flex footer'>
  Thank you for your Visit.
</footer>
{% endblock %}

Yummy_a_recipe_app/YummyProject/app/templates/search.html
{% extends "recipe_list.html" %}

{% block homepage %}
<a href="{%url 'list'%}" class="btn btn-secondary">Homepage</a>
{% endblock %}

{% block Portfolio %}{% endblock %}

{% block content2 %}
<h3 class="mt-4">Search Results - for {{query}} </h3>

{% endblock %}

Yummy_a_recipe_app/YummyProject/app/templates/view_recipe.html
{% extends "base.html" %}


{% block content %}
{% for item in recipe %}
<div class="recipe_name container my-2">
    
    <div class="row ">
        <div class="row view-name">
            {{item.recipe_name}}
        </div>
        <div class="row view-category mt-2">
            <div class="col-4">Category : </div>
            <div class="col-8">{{item.category}}</div>
        </div>
        <div class="row view-content mt-2">
            <div class="col-6">
                {% comment %} <pre>
                    {{item.text | linebreaks}}
                </pre> {% endcomment %}
                <p style="white-space: pre-wrap;">{{ item.text }}</p>
            </div>
            <div class="col-6 view-image">
                <img src="{{item.images.url}}" alt="">
            </div>
        </div>
       

    </div>
</div>


{% endfor %}

{% endblock %}
{% block Portfolio %}{% endblock %}